name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the problem
      placeholder: What is not working as expected?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the behavior
      placeholder: |
        1. Set up service with configuration '...'
        2. Execute HTTP request '...'
        3. Observe behavior '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The service should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happened instead?
      placeholder: The service instead...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Trace
      description: If available, paste logs, stack traces or error messages
      render: shell
      placeholder: |
        Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "user.name" is null
        at com.example.service.UserService.validateUser(UserService.java:45)
        at com.example.controller.AuthController.login(AuthController.java:28)....

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: v1.0.1 or commit hash
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, diagrams, or other useful information
      placeholder: Any other relevant information...